### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by abhijithsheheer** [abhijithsheheer/neeto-ui-challenge#6]

**Comment by abhijithsheheer** [comment]
Deployed on [https://abhijith-neetoui-challenge.herokuapp.com](https://abhijith-neetoui-challenge.herokuapp.com).
Can be logged in using:
Username : oliver@example.com
Password : welcome

**Comment by yedhink** [comment]
@abhijithsheheer LGTM. You can mark this task as completed and start with the next one.
